apiVersion: v1
kind: Template
labels:
  app: project-service
metadata:
  annotations:
    description: CoolStore project service persistent template for MongoDB
  name: coolstore-project-mongodb
objects:
# Project Service
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: project-service
    name: project-mongodb
  spec:
    ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      deploymentconfig: project-mongodb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: project-service
    name: project-mongodb
  spec:
    replicas: 1
    selector:
      deploymentconfig: project-mongodb
    strategy:
      recreateParams:
        post:
          execNewPod:
            command:
              - /bin/sh
              - -i
              - -c
              - sleep 10 && /opt/rh/rh-mongodb32/root/usr/bin/mongo $PROJECT_MONGODB_SERVICE_HOST:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="$MONGODB_INIT"
            containerName: project-mongodb
            env:
            - name: MONGODB_INIT
              value: db.project.insert({"_id":"111","projectid":111,"owner_firstname":"Red","owner_lastname":"Java","owner_email":"red@hotmail.com","project_description":"desc1","project_status":"open"});
                db.project.insert({"_id":"222","projectid":222,"owner_firstname":"Green","owner_lastname":"Php","owner_email":"green@gmail.com","project_description":"desc2","project_status":"in_progress"});
                db.project.insert({"_id":"333","projectid":333,"owner_firstname":"Blue","owner_lastname":"C","owner_email":"blue@hotmail.com","project_description":"desc3","project_status":"completed"});
                db.project.insert({"_id":"444","projectid":444,"owner_firstname":"Yellow","owner_lastname":"Phyton","owner_email":"yellow@gmail.com","project_description":"desc4","project_status":"cancelled"});
                db.project.insert({"_id":"555","projectid":555,"owner_firstname":"Dark","owner_lastname":"D","owner_email":"dark@gmail.com","project_description":"desc5","project_status":"open"});
                db.project.insert({"_id":"666","projectid":666,"owner_firstname":"Black","owner_lastname":"B","owner_email":"black@gmail.com","project_description":"desc6","project_status":"in_progress"});
          failurePolicy: ignore
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: project-service
          deploymentconfig: project-mongodb
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MONGODB_USER
            value: ${PROJECT_DB_USERNAME}
          - name: MONGODB_PASSWORD
            value: ${PROJECT_DB_PASSWORD}
          - name: MONGODB_DATABASE
            value: ${PROJECT_DATABASE}
          - name: MONGODB_ADMIN_PASSWORD
            value: ${PROJECT_DB_PASSWORD}
          image: mongodb
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: project-mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongodb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data-pv
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - project-mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:3.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      application: project-mongodb
    name: mongodb-data-pv
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
parameters:
- description: Project Service database user name
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: PROJECT_DB_USERNAME
  required: true
- description: Project Service database user password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: PROJECT_DB_PASSWORD
  required: true
- description: Project Service database name
  name: PROJECT_DATABASE
  required: true
  value: projectdb
